### ISSUE TITLE
Introduction to Vuex

### ISSUE THREAD

**Issue by doppelmutzi** [xiGUAwanOU/kvug#3]
Topic: Introduction to Vuex
Main question: What is Vuex, what are the underlying conceptional foundations, for what use cases is it useful

Contents:

- What is Vuex and its underlying concepts
- getters, mutations, actions
- demo project with different development stages (initially with no Vuex, then different aspects are added and explained)
- (maybe: future of Vuex)
- questions

**Comment by doppelmutzi** [comment]
October is to short dated ... I would like to give my talk in the meetup after the next. 
@xiGUAwanOU  Would this be January 2019?

**Comment by xiGUAwanOU** [comment]
Hey, thanks for the topic suggestion!

Just in case you don't know yet. We have already had an introduction of vuex in our 1st meetup. That one is more or less related to the best practices. A different view angle about vuex is definitely welcomed!

I also think October is too urgent. Probably the one after the next meetup will be in February next year since I'd like to avoid the new year vacations.

**Comment by doppelmutzi** [comment]
@xiGUAwanOU Oh sorry, I couldn't make it to the first meetup and I didn't read the information here carefully. I will close this issue.
However, I will check the content of the first Vuex talk and maybe I will come up with another Vuex talk. Or I will come up with a completely different opic.
